jobs:
  - name: sync-projects
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command: ["python", "manage.py", "sync_projects"]
    suspend: true
  - name: send-deadline-notifications
    schedule: "0 0 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command: ["python", "manage.py", "send_deadline_notifications"]
    suspend: true
  - name: send-suggestion-notifications
    schedule: "0 0 * * 6"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command: ["python", "manage.py", "send_suggestion_notifications"]
    suspend: true
  - name: send-review-notifications
    schedule: "0 6 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command: ["python", "manage.py", "send_review_notifications"]
    suspend: true
  - name: collect-insights
    schedule: "0 7 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command: ["python", "manage.py", "collect_insights"]
    suspend: true
  - name: clear-old-sync-logs
    schedule: "0 23 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    command: ["python", "manage.py", "clear_old_sync_logs"]
    suspend: true
