---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pontoon-helm.name" . }}
  labels:
    {{- include "pontoon-helm.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env.open }}
  {{ $key }}: {{ $value | toString | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pontoon-helm.name" . }}-nginx
  labels:
    {{- include "pontoon-helm.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/nginx.conf").AsConfig | indent 2 }}
