{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $release_name }}-{{ $job.name }}"
  labels:
    {{- include "pontoon-helm.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/type: cron
    app.kubernetes.io/cron: {{ $job.name }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  suspend: {{ $job.suspend }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "pontoon-helm.selectorLabels" $ | nindent 12 }}
            app.kubernetes.io/type: cron
            app.kubernetes.io/cron: {{ $job.name }}
        spec:
          serviceAccountName: {{ include "pontoon-helm.serviceAccountName" $ }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ $job.name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command: {{ $job.command }}
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              envFrom:
                - secretRef:
                    name: {{ template "pontoon-helm.name" $ }}
                - configMapRef:
                    name: {{ template "pontoon-helm.name" $ }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
{{- end }}
