apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    {{- include "pontoon-helm.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.auth | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pontoon-helm.name" . }}
  labels:
    {{- include "pontoon-helm.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.env.secrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}

